version: '3'
services:
   ubuntu:
        image: cuilongjin/my-ubuntu:1.5
        container_name: ubuntu
        command:
            - bt start # 启动宝塔
            - service aria2 start # 启动 aria2
            - service nginx start # 启动 nginx
        tty: true
        ports:
            - '80:80' # web
            - '8889:8889' # 宝塔
            - '6801:6800' # aria2 rpc
            - '6881:6880' # AriaNg
            - '33:33' # ssh
        volumes:
            - '/root/my-file:/root/my-file'
